import './globals.css';
import { getStoryblokApi } from '@/lib/storyblok';
import StoryblokProvider from '@/components/StoryblokProvider';
import { StoryblokServerComponent } from '@storyblok/react/rsc';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	const storyblokApi = getStoryblokApi();

	const { data } = await storyblokApi.get('cdn/stories/config', {
		version: 'draft',
		resolve_links: 'url',
	});

	const config = data.story.content;
	const headerBlok = config.header?.[0];
	const footerBlok = config.footer?.[0];

	return (
		<StoryblokProvider>
			<html lang="en">
				<body className="flex w-full mx-auto min-h-full flex-col">
					{headerBlok && <StoryblokServerComponent blok={headerBlok} />}
					{children}
					{footerBlok && <StoryblokServerComponent blok={footerBlok} />}
				</body>
			</html>
		</StoryblokProvider>
	);
}
